addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
before_script:
    - npm run setup-gadm;
    - npm run trim-data;
    - npm run setup-ghsl;
    - npm run trim-data;
    - npm run setup-mapspam;
    - npm run trim-data;
cache:
  directories:
    - "node_modules"
language: node_js
node_js:
  - "node"
  - "lts/*"
