addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
before_script:
    - npm run setup-gadm;
    - npm run trim-gadm;
    - df -H
    - npm run setup-ghsl;
    - npm run trim-ghsl;
    - df -H
    - npm run setup-mapspam;
cache:
  directories:
    - "node_modules"
language: node_js
node_js:
  - "node"
  - "lts/*"
